/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author gabrielstahlberg
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopArea = new javax.swing.JDesktopPane();
        labelLogo = new javax.swing.JLabel();
        labelUserOn = new javax.swing.JLabel();
        labelDataSection = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        itemCadBook = new javax.swing.JMenuItem();
        itemUsers = new javax.swing.JMenuItem();
        menuOption = new javax.swing.JMenu();
        itemBooks = new javax.swing.JMenuItem();
        itemLoan = new javax.swing.JMenuItem();
        itemDevolution = new javax.swing.JMenuItem();
        itemPendency = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IFSP Library System");
        setResizable(false);

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Logo.png"))); // NOI18N

        labelUserOn.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        labelUserOn.setText("Usuário");

        labelDataSection.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        labelDataSection.setText("Data");

        menuCad.setText("Cadastro");

        itemCadBook.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        itemCadBook.setText("Obras");
        menuCad.add(itemCadBook);

        itemUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itemUsers.setText("Usuários");
        itemUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsersActionPerformed(evt);
            }
        });
        menuCad.add(itemUsers);

        menuBar.add(menuCad);

        menuOption.setText("Opções");

        itemBooks.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        itemBooks.setText("Relatório do acervo");
        menuOption.add(itemBooks);

        itemLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemLoan.setText("Realizar empréstimo");
        menuOption.add(itemLoan);

        itemDevolution.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        itemDevolution.setText("Realizar devolução");
        menuOption.add(itemDevolution);

        itemPendency.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemPendency.setText("Consultar pendências");
        menuOption.add(itemPendency);

        itemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        itemExit.setText("Sair");
        menuOption.add(itemExit);

        menuBar.add(menuOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(desktopArea, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserOn)
                    .addComponent(labelDataSection))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(labelUserOn)
                        .addGap(38, 38, 38)
                        .addComponent(labelDataSection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(labelLogo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desktopArea)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(860, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopArea;
    private javax.swing.JMenuItem itemBooks;
    private javax.swing.JMenuItem itemCadBook;
    private javax.swing.JMenuItem itemDevolution;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemLoan;
    private javax.swing.JMenuItem itemPendency;
    private javax.swing.JMenuItem itemUsers;
    private javax.swing.JLabel labelDataSection;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelUserOn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCad;
    private javax.swing.JMenu menuOption;
    // End of variables declaration//GEN-END:variables
}
