/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ObrasDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.Obra;

/**
 *
 * @author gabrielstahlberg
 */
public class TelaCadastroObras extends javax.swing.JInternalFrame {
    private List<String> autores = new ArrayList<>(5);
    private List<String> palavrasChave = new ArrayList<>(5);
    /**
     * Creates new form JanelaUsuario
     */
    public TelaCadastroObras() {
        initComponents();
        buscaCategorias();
        
    }
    
    private void buscaCategorias(){
        ObrasDAO obrasDAO = new ObrasDAO();
        List<String> listaCategorias = obrasDAO.buscarCategoriasObra();
        for(int i=0; i<listaCategorias.size(); i++){
            this.comboCategoria.addItem(listaCategorias.get(i));
        }
    }
    
    private void cadastraObra(){
        if(validaCampos()){
            ObrasDAO obrasDAO = new ObrasDAO();
            String titulo = this.fieldTitulo.getText();
            String isbn = this.fieldIsbn.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate dataPubl = LocalDate.parse(fieldDataPubl.getText(), formatter);
            String editora = this.fieldEditora.getText();
            int nroEdicao = Integer.parseInt(this.fieldNEdicao.getText());
            String categoria = (String)this.comboCategoria.getSelectedItem();
            
            String codigoCat = obrasDAO.buscarCategoriasObraCod(categoria);
            
            Obra obra = new Obra(titulo, isbn, editora, dataPubl, this.autores, this.palavrasChave, nroEdicao, codigoCat);            
            System.out.println(obra.toString());
            
            obrasDAO.salvar(obra);
            
        }else{
            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente", null, 2);
        }
    }
    
    private boolean validaCampos(){
        boolean retorno = true;
        
        if(this.fieldDataPubl.equals("") || 
           this.fieldEditora.equals("")  || 
           this.fieldIsbn.equals("")     ||
           this.fieldNEdicao.equals("")  || 
           this.fieldTitulo.equals("")   ||
           this.autores.size() == 0      ||
           this.palavrasChave.size() == 0)
        {
            retorno = false;
        }
        return retorno;
    }
    
    private void limpaCampos(){
        this.fieldDataPubl.setText(null);
        this.fieldEditora.setText(null);
        this.fieldIsbn.setText(null);
        this.fieldNEdicao.setText(null);
        this.fieldTitulo.setText(null);
        this.fieldTitulo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonXML = new javax.swing.JButton();
        buttonJSON = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        fieldTitulo = new javax.swing.JTextField();
        labelAutor = new javax.swing.JLabel();
        fieldAutor = new javax.swing.JTextField();
        labelPalavraChave = new javax.swing.JLabel();
        fieldPalavraChave = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        labelISBN = new javax.swing.JLabel();
        fieldIsbn = new javax.swing.JTextField();
        labelDataPubl = new javax.swing.JLabel();
        fieldDataPubl = new javax.swing.JTextField();
        labelEditora = new javax.swing.JLabel();
        fieldEditora = new javax.swing.JTextField();
        labelNEdicao = new javax.swing.JLabel();
        fieldNEdicao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        buttonAddPalavra = new javax.swing.JButton();
        buttonAddAutor = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Obras");
        setPreferredSize(new java.awt.Dimension(600, 493));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("Importar por:");

        buttonXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/xml.png"))); // NOI18N
        buttonXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXMLActionPerformed(evt);
            }
        });

        buttonJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/json.png"))); // NOI18N
        buttonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJSONActionPerformed(evt);
            }
        });

        labelTitulo.setText("Título*");

        labelAutor.setText("Autor*");

        labelPalavraChave.setText("Palavra chave*");

        labelCategoria.setText("Categoria*");

        labelISBN.setText("ISBN*");
        labelISBN.setToolTipText("");

        labelDataPubl.setText("Data Publ.*");

        labelEditora.setText("Editora*");

        labelNEdicao.setText("Nº Edição*");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 14, 8));
        jLabel2.setText("* Campos Obrigatórios");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/if_Books_82262.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Noto Sans", 2, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 19, 158));
        jLabel4.setText("CADASTRO");

        buttonCadastrar.setBackground(new java.awt.Color(254, 254, 254));
        buttonCadastrar.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        buttonCadastrar.setForeground(new java.awt.Color(63, 187, 71));
        buttonCadastrar.setText("CADASTRAR");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });

        buttonAddPalavra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        buttonAddPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPalavraActionPerformed(evt);
            }
        });

        buttonAddAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_user.png"))); // NOI18N
        buttonAddAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAutor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPalavraChave)
                                    .addComponent(labelTitulo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonCadastrar)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelCategoria)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelNEdicao)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldNEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldTitulo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(fieldAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(fieldPalavraChave))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buttonAddPalavra)
                                                    .addComponent(buttonAddAutor))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(labelDataPubl)
                                                    .addComponent(labelEditora)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(labelISBN)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldEditora)
                            .addComponent(fieldDataPubl)
                            .addComponent(fieldIsbn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonXML)
                        .addGap(34, 34, 34)
                        .addComponent(buttonJSON)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonJSON)
                            .addComponent(buttonXML)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(fieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelISBN)
                    .addComponent(fieldIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAutor)
                            .addComponent(labelDataPubl)
                            .addComponent(fieldDataPubl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPalavraChave)
                                    .addComponent(fieldPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEditora)
                                    .addComponent(fieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelCategoria)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNEdicao)
                                    .addComponent(fieldNEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(buttonCadastrar))))
                            .addComponent(buttonAddPalavra)))
                    .addComponent(buttonAddAutor))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setBounds(0, 0, 608, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXMLActionPerformed
        OpcoesXML opcoesXML = new OpcoesXML(true);
        opcoesXML.setVisible(true);
    }//GEN-LAST:event_buttonXMLActionPerformed

    private void buttonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJSONActionPerformed
        OpcoesJSON opcoesJSON = new OpcoesJSON();
        opcoesJSON.setVisible(true);
    }//GEN-LAST:event_buttonJSONActionPerformed

    private void buttonAddAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAutorActionPerformed
        if(!this.fieldAutor.getText().equals("")){
            this.autores.add(this.fieldAutor.getText());
            this.fieldAutor.setText(null);
            this.fieldAutor.requestFocus();
        }
    }//GEN-LAST:event_buttonAddAutorActionPerformed

    private void buttonAddPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPalavraActionPerformed
        if(!this.fieldPalavraChave.getText().equals("")){
            this.palavrasChave.add(this.fieldPalavraChave.getText());
            this.fieldPalavraChave.setText(null);
            this.fieldPalavraChave.requestFocus(true);
        }
    }//GEN-LAST:event_buttonAddPalavraActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        cadastraObra();
        limpaCampos();
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddAutor;
    private javax.swing.JButton buttonAddPalavra;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton buttonJSON;
    private javax.swing.JButton buttonXML;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JTextField fieldAutor;
    private javax.swing.JTextField fieldDataPubl;
    private javax.swing.JTextField fieldEditora;
    private javax.swing.JTextField fieldIsbn;
    private javax.swing.JTextField fieldNEdicao;
    private javax.swing.JTextField fieldPalavraChave;
    private javax.swing.JTextField fieldTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelAutor;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelDataPubl;
    private javax.swing.JLabel labelEditora;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelNEdicao;
    private javax.swing.JLabel labelPalavraChave;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
