/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ObrasDAO;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Obra;

/**
 *
 * @author gabrielstahlberg
 */
public class TelaRelatorio extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAcervo = new javax.swing.JTable();
        buttonAnterior = new javax.swing.JButton();
        buttonProximo = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        buttonAcervo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonXML = new javax.swing.JButton();
        buttonPDF = new javax.swing.JButton();
        buttonJSON = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tableAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Palavra Chave", "ISBN", "Data Publ.", "Editora", "Categoria", "Nº Edição", "Total Exemplares", "Total Disp."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAcervo.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableAcervo);

        buttonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/previous.png"))); // NOI18N

        buttonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Noto Sans", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 19, 158));
        jLabel7.setText("RELATÓRIO DO ACERVO");

        buttonAcervo.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        buttonAcervo.setForeground(new java.awt.Color(63, 187, 71));
        buttonAcervo.setText("GERAR RELATÓRIO");
        buttonAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcervoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("Exportar como:");

        buttonXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/xml.png"))); // NOI18N
        buttonXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXMLActionPerformed(evt);
            }
        });

        buttonPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pdf.png"))); // NOI18N
        buttonPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPDFActionPerformed(evt);
            }
        });

        buttonJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/json.png"))); // NOI18N
        buttonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJSONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonAnterior)
                                .addGap(149, 149, 149)
                                .addComponent(buttonAcervo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonProximo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(buttonXML)
                .addGap(28, 28, 28)
                .addComponent(buttonJSON)
                .addGap(27, 27, 27)
                .addComponent(buttonPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonProximo)
                    .addComponent(buttonAnterior)
                    .addComponent(buttonAcervo))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPDF)
                    .addComponent(buttonXML)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addComponent(buttonJSON))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setBounds(0, 0, 608, 493);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXMLActionPerformed
        OpcoesXML opcoesXML = new OpcoesXML(false);
        opcoesXML.setVisible(true);
    }//GEN-LAST:event_buttonXMLActionPerformed

    private void buttonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonJSONActionPerformed
        OpcoesJSON opcoesJSON = new OpcoesJSON();
        opcoesJSON.setVisible(true);
    }//GEN-LAST:event_buttonJSONActionPerformed

    private void buttonPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPDFActionPerformed
        OpcoesPDF opcoesPDF = new OpcoesPDF();
        opcoesPDF.setVisible(true);
    }//GEN-LAST:event_buttonPDFActionPerformed

    private void buttonAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcervoActionPerformed
        ObrasDAO oDAO = new ObrasDAO();
        List<Obra> obras = oDAO.realizarRelatorio(0, 10);
        
        //Aqui precisa integrar com a interface e fazer a paginação
        
        
    }//GEN-LAST:event_buttonAcervoActionPerformed

    private String arrumarLists(List<String> lista){
        StringBuilder build = new StringBuilder();
        lista.forEach(s -> build.append(String.format("%s,",s)));
        return build.toString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcervo;
    private javax.swing.JButton buttonAnterior;
    private javax.swing.JButton buttonJSON;
    private javax.swing.JButton buttonPDF;
    private javax.swing.JButton buttonProximo;
    private javax.swing.JButton buttonXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAcervo;
    // End of variables declaration//GEN-END:variables
}
